name: Build Python

on:
  push:
    branches:
      - main
    paths:
      - "python/**"
      - ".github/workflows/python.yaml"
      - "install_tooling.sh"
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: loft-sh/devspace-containers/python

defaults:
  run:
    working-directory: python

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 3-alpine
          - tag: 3.7-alpine
          - tag: 3.8-alpine
          - tag: 3.9-alpine
          - tag: 3.10-alpine
          - tag: 3.11-alpine
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: loft-sh/setup-devspace@main
      - run: devspace build --var TAG=${{ matrix.tag }}
